version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>      
        LoadBalancerInfo:
          ContainerName: "my-app-container"
          ContainerPort: 80
